import type { HomePageModel } from '@/lib/page-models/home'
import type { AboutPageModel, LorePageModel } from '@/lib/page-models/info'
import type { DepartmentsPageModel, DepartmentPageModel } from '@/lib/page-models/departments'
import type { CharacterProfilePageModel } from '@/lib/page-models/characterProfile'
import type { DocumentDesignViewProps } from '@/lib/design/types'
import { getDocumentActions } from '@/lib/documents/presentation/actions'
import { Heading, Html, Empty, Destinations } from './primitives'
import s from './atelier.module.css'

export function AtelierHome(p: HomePageModel) {
  return <><div className={s.homeHero}><p className={s.eyebrow}>01 / HOME</p><div className={s.heroTitle}><h1>{p.domain.name}</h1><span className={s.seal} aria-hidden="true">A<span>✳</span></span></div><div className={s.heroLower}><p>{p.domain.motto}</p><a href={`${p.baseUrl}/records`}>Browse records <span aria-hidden="true">↗</span></a></div></div>
    <div className={s.editorial}><section><p className={s.eyebrow}>WELCOME</p>{p.welcome.html ? <Html html={p.welcome.html} /> : <Empty>No welcome has been written yet.</Empty>}{p.welcome.editHref && <a className={s.textLink} href={p.welcome.editHref}>Edit welcome ↗</a>}</section><section className={s.indexPanel}><p className={s.eyebrow}>EXPLORE THE DOMAIN</p><Destinations items={p.destinations} /></section></div>
    <section className={s.recent}><div className={s.sectionHead}><h2>Recent records</h2><a href={`${p.baseUrl}/records`}>View all ↗</a></div>{p.recentRecords.length ? p.recentRecords.map((r, i) => <a className={s.recordLink} key={r.id} href={`${p.baseUrl}/documents/${r.id}`}><span className={s.ordinal}>{String(i + 1).padStart(2, '0')}</span><div><span className={s.eyebrow}>{r.type}</span><h3>{r.title}</h3></div><span className={s.muted}>{r.activity}</span><span aria-hidden="true">↗</span></a>) : <Empty>No recent records.</Empty>}</section></>
}
export function AtelierAbout(p: AboutPageModel) { return <><Heading number="02" title="About" actions={p.editHref && <a className={s.button} href={p.editHref}>Edit page ↗</a>} /><div className={s.reading}>{p.bodyHtml ? <Html html={p.bodyHtml} /> : <Empty>No page content yet.</Empty>}</div><Destinations items={p.destinations} /></> }
export function AtelierLore(p: LorePageModel) { return <><Heading number="03" title="Lore" /><div className={s.cards}>{p.entries.map((entry, i) => <article className={s.card} key={entry.slug}><p className={s.eyebrow}>{String(i + 1).padStart(2, '0')} / {entry.group || 'LORE'}</p><h2><a href={entry.href}>{entry.title} ↗</a></h2>{entry.summary && <p>{entry.summary}</p>}{entry.revisionLabel && <small>{entry.revisionLabel}</small>}<details><summary>Read entry</summary><Html html={entry.bodyHtml} /></details></article>)}</div>{!p.entries.length && <Empty>No published lore yet.</Empty>}<Destinations items={p.destinations} /></> }
export function AtelierDepartments(p: DepartmentsPageModel) { return <><Heading number="04" title={p.vocabulary.subdomainPlural} actions={p.manageHref && <a className={s.button} href={p.manageHref}>Manage ↗</a>} /><div className={s.cards}>{p.departments.map((d, i) => <article className={s.card} key={d.id}><p className={s.eyebrow}>{String(i + 1).padStart(2, '0')} / {p.vocabulary.subdomainSingular}</p><h2><a href={`${p.baseUrl}/departments/${d.slug}`}>{d.name} ↗</a></h2>{d.description && <p>{d.description}</p>}<span className={s.badge}>{d.memberCount} members</span></article>)}</div>{!p.departments.length && <Empty>No {p.vocabulary.subdomainPlural.toLowerCase()} yet.</Empty>}</> }
export function AtelierDepartment(p: DepartmentPageModel) { return <><Heading number="04" title={p.name} actions={p.manageHref && <a className={s.button} href={p.manageHref}>Manage ↗</a>}>{p.description}</Heading><div className={s.editorial}><section><h2>{p.vocabulary.memberPlural}</h2>{p.members.map(m => <div className={s.row} key={m.id}><strong>{m.name}</strong>{m.role && <span className={s.muted}>{m.role}</span>}</div>)}{!p.members.length && <Empty>No members listed.</Empty>}</section><section className={s.indexPanel}><h2>{p.vocabulary.folderPlural}</h2>{p.folderNames.map((f, i) => <p className={s.row} key={`${f}-${i}`}>{f}</p>)}{!p.folderNames.length && <Empty>No visible folders.</Empty>}</section></div><Destinations items={p.destinations} /></> }
export function AtelierCharacterProfile(p: CharacterProfilePageModel) { return <><Heading number="07" title={p.character.name} actions={<a className={s.button} href={p.backHref}>Members ↗</a>}>{p.roleName}</Heading><div className={s.editorial}><section className={s.reading}><p className={s.eyebrow}>{p.character.kind} / {p.character.status}</p><p className={s.intro}>{p.focus}</p></section><section className={s.indexPanel}><h2><a href={p.departmentHref}>{p.departmentName} ↗</a></h2><p>{p.departmentDescription}</p></section></div></> }
export function AtelierDocument(p: DocumentDesignViewProps) {
  const actions = getDocumentActions(p, { workflow: !!p.workflowAction, delete: !!p.deleteAction })
  return <><Heading number="05" title={p.title}><span className={s.badge}>{p.lifecycle}{p.locked ? ' / Locked' : ''}{p.isSuperseded ? ' / Superseded' : ''}</span></Heading>
    {p.statusMessage && <p className={s.notice} role="status">{p.statusMessage.text}</p>}
    <div className={s.actions}>{actions.map(a => a.href ? <a className={s.button} key={a.operation} href={a.href}>{a.label}</a> : <form key={a.operation} action={(a.operation === 'delete' ? p.deleteAction : p.workflowAction) ?? undefined}><input type="hidden" name="tenantSlug" value={p.domainSlug} /><input type="hidden" name="documentId" value={p.recordId} /><input type="hidden" name="operation" value={a.operation} /><button type="submit" className={s.button}>{a.label}</button></form>)}</div>
    <div className={s.documentGrid}><aside className={s.metadata}><p className={s.eyebrow}>RECORD NOTES</p><dl>{p.meta.map((m, i) => <div key={i}><dt>{m.label}</dt><dd>{m.value}</dd></div>)}</dl><p>{p.preparedByLabel}</p>{p.tags.map(t => <span className={s.badge} key={t}>{t}</span>)}{p.concerns.map((c, i) => <p key={i}>{c.name}{c.relationshipLabel && ` / ${c.relationshipLabel}`}</p>)}{p.supersession.supersedes && <p>Supersedes <a href={`${p.baseUrl}/documents/${p.supersession.supersedes.id}`}>{p.supersession.supersedes.title}</a></p>}{p.supersession.supersededBy && <p>Superseded by <a href={`${p.baseUrl}/documents/${p.supersession.supersededBy.id}`}>{p.supersession.supersededBy.title}</a><br />{p.supersession.supersededBy.createdLabel} · {p.supersession.supersededBy.preparedByLabel}</p>}</aside><article className={s.reading}><Html html={p.bodyHtml} />{p.bodySource !== null && <details><summary>View source</summary><pre>{p.bodySource}</pre></details>}</article></div></>
}
