'use client'
import { useState } from 'react'
import type { RecordsPageModel } from '@/lib/page-models/records'
import type { MembersPageModel } from '@/lib/page-models/members'
import type { DepartmentsManagementPageModel } from '@/lib/page-models/management/departments'
import type { FolderManagementPageModel } from '@/lib/page-models/management/folders'
import type { RoleManagementPageModel } from '@/lib/page-models/management/roles'
import type { DocumentTypesManagementPageModel } from '@/lib/page-models/management/documentTypes'
import type { PeopleManagementPageModel, PersonManagementPageModel } from '@/lib/page-models/management/people'
import type { InvitationsManagementPageModel } from '@/lib/page-models/management/invitations'
import type { WorkDesignViewProps } from '@/lib/design/types'
import type { FolderSummary } from '@/lib/page-models/common'
import { Heading, Empty, Status } from './primitives'
import s from './atelier.module.css'

function PendingConnection(){return <p className={s.muted}>Design preview · editing connections will follow the host-contract freeze.</p>}
export function AtelierRecords(p:RecordsPageModel){
 const [query,setQuery]=useState(p.query.search),[folder,setFolder]=useState<number|null>(p.query.folderId),[sort,setSort]=useState('recent')
 const flat=(nodes:FolderSummary[]):FolderSummary[]=>nodes.flatMap(n=>[n,...flat(n.children)])
 const folders=flat(p.folders),selected=folders.find(f=>f.id===folder)
 const rows=p.records.filter(r=>(folder===null||r.folderId===folder)&&r.title.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):b.updatedAt.localeCompare(a.updatedAt))
 const tree=(nodes:FolderSummary[],depth=0):React.ReactNode=>nodes.map(n=><div key={n.id}><button style={{paddingLeft:8+depth*12}} aria-pressed={folder===n.id} onClick={()=>setFolder(n.id)}>{n.name} <span className={s.muted}>({n.readableRecordCount})</span></button>{tree(n.children,depth+1)}</div>)
 return <><Heading number="05" title={p.vocabulary.documentPlural}><span className={s.muted}>The working archive. Find a record, follow its history.</span></Heading><div className={s.workspace}><aside className={s.tree}><p className={s.eyebrow}>{p.vocabulary.folderPlural}</p><button aria-pressed={folder===null} onClick={()=>setFolder(null)}>All records</button>{tree(p.folders)}</aside><section><div className={s.toolbar}><input aria-label="Search records" placeholder="Search the archive…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Sort records" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Recently updated</option><option value="title">Title A–Z</option></select></div><div className={s.sectionHead}><h2>{selected?.name??'All records'}</h2><span className={s.muted}>{rows.length} records in this preview</span></div>{rows.length?rows.map((r,i)=><a className={s.recordLink} key={r.id} href={`${p.baseUrl}/documents/${r.id}`}><span className={s.ordinal}>{String(i+1).padStart(2,'0')}</span><div><span className={s.eyebrow}>{p.documentTypes.find(t=>t.id===r.documentTypeId)?.name??'Record'} / {r.lifecycle}{r.locked?' / Locked':''}</span><h3>{r.title}</h3><span className={s.muted}>{r.preparedBy??'—'}</span></div><span aria-hidden="true">↗</span></a>):<Empty>No records match this view.</Empty>}</section></div></>
}
export function AtelierMembers(p:MembersPageModel){const[q,setQ]=useState('');const rows=p.rows.filter(r=>`${r.name} ${r.roles.join(' ')}`.toLowerCase().includes(q.toLowerCase()));return <><Heading number="07" title={p.vocabulary.memberPlural}>The people behind the work.</Heading><Status status={p.status}/><div className={s.toolbar}><input aria-label="Filter members" placeholder="Find a member…" value={q} onChange={e=>setQ(e.target.value)}/><span>{rows.length} members</span></div><div className={s.cards}>{rows.map(r=><article className={s.card} key={r.membershipId}><div className={s.personName}><span className={s.avatar}>{r.name.slice(0,1)}</span><h3><a href={`${p.baseUrl}/characters/${r.characterId}`}>{r.localDisplayName||r.name} ↗</a></h3></div><p className={s.eyebrow} style={{marginTop:24}}>{r.departments.join(' / ')||'Member'}</p><p>{r.roles.join(', ')||'No roles listed'}</p><span className={s.badge}>{r.membershipStatus}</span></article>)}</div>{!rows.length&&<Empty>No members match your search.</Empty>}</>}
export function AtelierManageDepartments(p:DepartmentsManagementPageModel){return <><Heading number="08" title={p.vocabulary.subdomainPlural}>Organization / administration</Heading><Status status={p.status}/><div className={s.cards}>{p.departments.map((d,i)=><article className={s.card} key={d.id}><p className={s.eyebrow}>{String(i+1).padStart(2,'0')} / {d.archived?'Archived':'Active'}</p><h2><a href={`${p.baseUrl}/departments/${d.slug}`}>{d.name} ↗</a></h2><p className={s.muted}>{d.slug}</p></article>)}</div>{!p.departments.length&&<Empty>No departments yet.</Empty>}<PendingConnection/></>}
export function AtelierFolders(p:FolderManagementPageModel){const[selected,setSelected]=useState<number|null>(null);const render=(nodes:FolderManagementPageModel['nodes'],depth=0):React.ReactNode=>nodes.map(n=><div key={n.id}><div className={s.row} style={{paddingLeft:depth*24}}><button onClick={()=>setSelected(n.id)} aria-pressed={selected===n.id}>↳ {n.name}</button><span className={s.badge}>{n.systemManaged?'System managed':'Folder'}</span></div>{render(n.children,depth+1)}</div>);return <><Heading number="09" title="Folders">A place for everything in the archive.</Heading><Status status={p.status}/><div className={s.panel}>{render(p.nodes)}{!p.nodes.length&&<Empty>No folders yet.</Empty>}</div><PendingConnection/></>}
export function AtelierRoles(p:RoleManagementPageModel){const[id,setId]=useState<number|null>(p.initialRoleId??p.roleRecords[0]?.id??null);const role=p.roleRecords.find(r=>r.id===id);return <><Heading number="10" title="Roles">Responsibilities, people, and access.</Heading><Status status={p.status}/><div className={s.workspace}><aside className={s.tree}>{p.departments.map(d=><section key={d.id}><p className={s.eyebrow}>{d.name}</p>{p.roleRecords.filter(r=>r.departmentId===d.id).map(r=><button key={r.id} aria-pressed={id===r.id} onClick={()=>setId(r.id)}>{r.name}</button>)}</section>)}</aside><section>{role?<><p className={s.eyebrow}>ROLE DETAILS</p><h2>{role.name}</h2><div className={s.panel}><h3>Current holders</h3>{(p.holdersByRole[String(role.id)]??[]).map(h=><a className={s.row} key={h.id} href={`${p.baseUrl}/manage/people/${h.id}`}>{h.name} ↗</a>)}{!p.holdersByRole[String(role.id)]?.length&&<p>No current holders.</p>}</div><h3>Document types</h3>{p.types.map(t=><div className={s.row} key={t.id}>{t.name}</div>)}<PendingConnection/></>:<Empty>Select a role to inspect it.</Empty>}</section></div></>}
export function AtelierDocumentTypes(p:DocumentTypesManagementPageModel){const[id,setId]=useState<number|null>(p.tree.types[0]?.id??null);const type=p.tree.types.find(t=>t.id===id);return <><Heading number="11" title="Document types">The forms your knowledge takes.</Heading><Status status={p.status}/><div className={s.workspace}><aside className={s.tree}><p className={s.eyebrow}>TYPE INDEX</p>{p.tree.types.map(t=><button key={t.id} aria-pressed={id===t.id} onClick={()=>setId(t.id)}>{t.name}</button>)}</aside><section>{type?<><span className={s.badge}>{type.active?'Active':'Inactive'}</span><h2 style={{marginTop:20}}>{type.name}</h2><p>{type.description||'No description provided.'}</p><div className={s.panel}><p className={s.eyebrow}>TEMPLATE</p><h3>{type.templateName??type.templateSelection}</h3><p className={s.muted}>{type.templateKind??'Blank document'}</p></div><PendingConnection/></>:<Empty>No document types yet.</Empty>}</section></div></>}
export function AtelierPeople(p:PeopleManagementPageModel){return <><Heading number="12" title="People">Identity, membership, and individual access.</Heading><Status status={p.status}/>{p.canOpenPeople?<div className={s.reading}><h2>Find your people.</h2><p>Browse the domain directory to explore its members and their roles.</p><a className={s.button} href={`${p.baseUrl}/members`}>Open member directory ↗</a><div style={{marginTop:28}}><PendingConnection/></div></div>:<Empty>You do not have access to this workspace.</Empty>}</>}
export function AtelierPerson(p:PersonManagementPageModel){return <><Heading number="12" title={p.localDisplayName||p.character.name}><span className={s.badge}>{p.character.kind} / {p.character.status}</span></Heading><Status status={p.status}/><div className={s.split}><section className={s.panel}><p className={s.eyebrow}>IDENTITY</p><h2>{p.character.name}</h2><p>Controller: {p.controller?.name||p.controller?.email||'Unclaimed'}</p></section><section className={s.panel}><p className={s.eyebrow}>PARTICIPATION</p>{p.roleDepartments.map(d=><p className={s.row} key={d.id}>{d.name}</p>)}</section></div><h2>Document access</h2><div className={s.tableWrap}><table className={s.table}><thead><tr><th>Type</th><th>Read</th><th>Create</th><th>Edit</th></tr></thead><tbody>{p.typeAccess.map(t=><tr key={t.id}><td>{t.name}</td>{(['read','create','edit'] as const).map(k=><td key={k}>{t[k].allowed?'Allowed':'Not allowed'}<br/><span className={s.muted}>{t[k].source}</span></td>)}</tr>)}</tbody></table></div></>}
export function AtelierInvitations(p:InvitationsManagementPageModel){return <><Heading number="13" title="Invitations">Open doors. Thoughtful introductions.</Heading><Status status={p.status}/>{p.canManage?<><div className={s.stats}><div><strong>{p.invitations.length}</strong>Invitations</div><div><strong>{p.pendingJoins.length}</strong>Join requests</div><div><strong>{p.pendingClaims.length}</strong>Character claims</div></div><div className={s.tableWrap}><table className={s.table}><thead><tr><th>Invitation</th><th>Purpose</th><th>Status</th><th>Expires</th></tr></thead><tbody>{p.invitations.map(i=><tr key={i.id}><td>{i.targetLabel}<br/><span className={s.muted}>{i.issuedByLabel}</span></td><td>{i.purpose}</td><td><span className={s.badge}>{i.statusLabel}</span><br/>{i.useLabel}</td><td>{i.expiresLabel}</td></tr>)}</tbody></table></div><div className={s.split} style={{marginTop:30}}><section><h2>Join requests</h2>{p.pendingJoins.map(j=><p className={s.row} key={j.id}>{j.applicantLabel} / {j.characterLabel}</p>)}{!p.pendingJoins.length&&<Empty>No pending requests.</Empty>}</section><section><h2>Character claims</h2>{p.pendingClaims.map(c=><p className={s.row} key={c.id}>{c.claimantLabel} / {c.characterLabel}</p>)}{!p.pendingClaims.length&&<Empty>No pending claims.</Empty>}</section></div><PendingConnection/></>:<Empty>You do not have access to invitations.</Empty>}</>}
export function AtelierWork(p:WorkDesignViewProps){return <><Heading number="06" title="Work">What needs your attention.</Heading><Status status={p.status}/>{p.authorized?<>{p.entries.map((e,i)=><article className={s.recordLink} key={`${e.kind}-${e.id}`}><span className={s.ordinal}>{String(i+1).padStart(2,'0')}</span><div><p className={s.eyebrow}>{e.kind}{e.folderName?` / ${e.folderName}`:''}</p><h3>{e.href?<a href={e.href}>{e.title} ↗</a>:e.title}</h3><p className={s.muted}>{e.summary}</p></div></article>)}{!p.entries.length&&<Empty>All caught up. Nothing needs your attention.</Empty>}<PendingConnection/></>:<Empty>You do not have access to this work queue.</Empty>}</>}
