'use client'
import { useState } from 'react'
import type { RecordsPageModel } from '@/lib/page-models/records'
import type { MembersPageModel } from '@/lib/page-models/members'
import type { FolderSummary } from '@/lib/page-models/common'
import { Heading, Empty, Status } from './primitives'
import s from './atelier.module.css'
import { importNotecardHref } from '@/lib/records/presentation/operations'

export function AtelierRecords(p:RecordsPageModel){
 const [query,setQuery]=useState(p.query.search),[folder,setFolder]=useState<number|null>(p.query.folderId),[sort,setSort]=useState('recent'),[subfolders,setSubfolders]=useState(false),[typeId,setTypeId]=useState('')
 const flat=(nodes:FolderSummary[]):FolderSummary[]=>nodes.flatMap(n=>[n,...flat(n.children)])
 const folders=flat(p.folders),selected=folders.find(f=>f.id===folder)
 const descendants=(nodes:FolderSummary[]):number[]=>nodes.flatMap(n=>n.id===folder?[n.id,...flat(n.children).map(c=>c.id)]:descendants(n.children))
 const folderIds=folder===null?null:new Set(subfolders?descendants(p.folders):[folder])
 const rows=p.records.filter(r=>(folderIds===null||r.folderId!==null&&folderIds.has(r.folderId))&&r.title.toLowerCase().includes(query.toLowerCase())&&(typeId===''||String(r.documentTypeId)===typeId)).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):b.updatedAt.localeCompare(a.updatedAt))
 const tree=(nodes:FolderSummary[],depth=0):React.ReactNode=>nodes.map(n=><div key={n.id}><button style={{paddingLeft:8+depth*12}} aria-pressed={folder===n.id} onClick={()=>setFolder(n.id)}>{n.name} <span className={s.muted}>({n.readableRecordCount})</span></button>{tree(n.children,depth+1)}</div>)
 return <><Heading title={p.vocabulary.documentPlural}><span className={s.muted}>The working archive. Find a record, follow its history.</span></Heading><div className={s.workspace}><aside className={s.tree}><p className={s.eyebrow}>{p.vocabulary.folderPlural}</p><button aria-pressed={folder===null} onClick={()=>setFolder(null)}>All records</button>{tree(p.folders)}<div className={s.actions}><a className={s.button} href={`${p.baseUrl}/manage/folders`}>Create folder</a><a className={s.button} href={`${p.baseUrl}/manage/folders`}>Rename folder</a><a className={s.button} href={`${p.baseUrl}/manage/folders`}>Delete folder</a></div></aside><section><div className={s.toolbar}><input aria-label="Search records" type="search" placeholder="Search the archive…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Sort records" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Recently updated</option><option value="title">Title A–Z</option></select><label className={s.muted}><input type="checkbox" checked={subfolders} onChange={e=>setSubfolders(e.target.checked)}/>Search subfolders</label><select aria-label="Document type filter" value={typeId} onChange={e=>setTypeId(e.target.value)}><option value="">All types</option>{p.documentTypes.map(t=><option key={t.id} value={String(t.id)}>{t.name}</option>)}</select><a className={s.button} href={`${p.baseUrl}/records/new`}>New document</a><a className={s.button} href={importNotecardHref(p.baseUrl)}>Import notecard</a></div><div className={s.sectionHead}><h2>{selected?.name??'All records'}</h2><span className={s.muted}>{rows.length} records in this preview</span></div>{rows.length?rows.map((r)=><div key={r.id}><a className={s.recordLink} href={`${p.baseUrl}/documents/${r.id}`}><div><span className={s.eyebrow}>{p.documentTypes.find(t=>t.id===r.documentTypeId)?.name??'Record'} / {r.lifecycle}{r.locked?' / Locked':''}{p.supersessionEdges.some(e=>e.olderId===r.id)?' / Superseded':''}</span><h3>{r.title}</h3><span className={s.muted}>{r.preparedBy??'—'}</span></div></a><div className={s.actions}>{r.capabilities.edit&&<a className={s.button} href={`${p.baseUrl}/documents/${r.id}/edit`}>Edit</a>}{r.capabilities.supersede&&<a className={s.button} href={`${p.baseUrl}/records/new?supersedes=${r.id}`}>Supersede</a>}{r.capabilities.delete&&<a className={s.button} href={`${p.baseUrl}/documents/${r.id}`}>Delete</a>}</div></div>):<Empty>No records match this view.</Empty>}</section></div></>
}
export function AtelierMembers(p:MembersPageModel){const[q,setQ]=useState('');const rows=p.rows.filter(r=>`${r.name} ${r.roles.join(' ')}`.toLowerCase().includes(q.toLowerCase()));return <><Heading title={p.vocabulary.memberPlural}></Heading><Status status={p.status}/><div className={s.toolbar}><input aria-label="Filter members" placeholder="Find a member…" value={q} onChange={e=>setQ(e.target.value)}/><span>{rows.length} members</span></div><div className={s.cards}>{rows.map(r=><article className={s.card} key={r.membershipId}><div className={s.personName}><span className={s.avatar}>{r.name.slice(0,1)}</span><h3><a href={`${p.baseUrl}/characters/${r.characterId}`}>{r.localDisplayName||r.name}</a></h3></div><p className={s.eyebrow} style={{marginTop:24}}>{r.departments.join(' / ')||'Member'}</p><p>{r.roles.join(', ')||'No roles listed'}</p><span className={s.badge}>{r.membershipStatus}</span></article>)}</div>{!rows.length&&<Empty>No members match your search.</Empty>}</>}

export { AtelierManageDepartments, AtelierFolders, AtelierRoles, AtelierDocumentTypes, AtelierPeople, AtelierPerson, AtelierInvitations, AtelierWork } from './management'
