/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    characters: Character;
    'character-claim-requests': CharacterClaimRequest;
    'character-merge-requests': CharacterMergeRequest;
    'domain-character-contexts': DomainCharacterContext;
    'domain-memberships': DomainMembership;
    domains: Domain;
    'domain-admins': DomainAdmin;
    subdomains: Subdomain;
    'subdomain-memberships': SubdomainMembership;
    roles: Role;
    'role-assignments': RoleAssignment;
    'document-types': DocumentType;
    'document-provenance-events': DocumentProvenanceEvent;
    tenants: Tenant;
    memberships: Membership;
    documents: Document;
    folders: Folder;
    pages: Page;
    media: Media;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    'character-claim-requests': CharacterClaimRequestsSelect<false> | CharacterClaimRequestsSelect<true>;
    'character-merge-requests': CharacterMergeRequestsSelect<false> | CharacterMergeRequestsSelect<true>;
    'domain-character-contexts': DomainCharacterContextsSelect<false> | DomainCharacterContextsSelect<true>;
    'domain-memberships': DomainMembershipsSelect<false> | DomainMembershipsSelect<true>;
    domains: DomainsSelect<false> | DomainsSelect<true>;
    'domain-admins': DomainAdminsSelect<false> | DomainAdminsSelect<true>;
    subdomains: SubdomainsSelect<false> | SubdomainsSelect<true>;
    'subdomain-memberships': SubdomainMembershipsSelect<false> | SubdomainMembershipsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'role-assignments': RoleAssignmentsSelect<false> | RoleAssignmentsSelect<true>;
    'document-types': DocumentTypesSelect<false> | DocumentTypesSelect<true>;
    'document-provenance-events': DocumentProvenanceEventsSelect<false> | DocumentProvenanceEventsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    folders: FoldersSelect<false> | FoldersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Optional identity placeholder. Verification is not enabled yet.
   */
  slAvatarUUID?: string | null;
  slAvatarName?: string | null;
  slVerificationState: 'unlinked' | 'pending' | 'verified';
  slVerifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  name: string;
  portrait?: (number | null) | Media;
  bio?: string | null;
  /**
   * Leave empty for an unclaimed or Domain-managed Character.
   */
  controlledBy?: (number | null) | User;
  status: 'active' | 'inactive' | 'merged';
  mergedInto?: (number | null) | Character;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "character-claim-requests".
 */
export interface CharacterClaimRequest {
  id: number;
  character: number | Character;
  claimant: number | User;
  tenant: number | Tenant;
  status: 'pending' | 'approved' | 'rejected' | 'cancelled';
  requestedAt: string;
  decidedAt?: string | null;
  decidedBy?: (number | null) | User;
  decidingCharacter?: (number | null) | Character;
  decisionNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * URL identifier, e.g. ravenhurst
   */
  slug: string;
  motto?: string | null;
  preset: 'heritage' | 'modern';
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  headingFontKey: 'georgia' | 'palatino' | 'verdana' | 'trebuchet';
  bodyFontKey: 'verdana' | 'georgia' | 'trebuchet' | 'tahoma';
  /**
   * Optional Domain seal or logo (image).
   */
  logo?: (number | null) | Media;
  /**
   * Optional header banner (image).
   */
  banner?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "character-merge-requests".
 */
export interface CharacterMergeRequest {
  id: number;
  source: number | Character;
  /**
   * Optional at request time; required before approval.
   */
  target?: (number | null) | Character;
  tenant: number | Tenant;
  requestingUser: number | User;
  requestingCharacter?: (number | null) | Character;
  evidence: string;
  note: string;
  status: 'pending' | 'approved' | 'rejected' | 'blocked';
  decidingPlatformAdmin?: (number | null) | User;
  decisionReason?: string | null;
  requestedAt: string;
  decidedAt?: string | null;
  impactPreviewHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domain-character-contexts".
 */
export interface DomainCharacterContext {
  id: number;
  /**
   * Canonical Domain relationship. Populated by the Phase 3 migration.
   */
  domain?: (number | null) | Domain;
  tenant?: (number | null) | Tenant;
  character: number | Character;
  localDisplayName: string;
  localNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains".
 */
export interface Domain {
  id: number;
  name: string;
  slug: string;
  kind: 'community' | 'personal';
  ownerUser?: (number | null) | User;
  ownerCharacter?: (number | null) | Character;
  lifecycle: 'active' | 'grace' | 'read-only' | 'suspended' | 'archived';
  defaultFilingPolicy: 'direct-file' | 'review-required';
  motto?: string | null;
  preset: 'heritage' | 'modern';
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  headingFontKey: 'georgia' | 'palatino' | 'verdana' | 'trebuchet';
  bodyFontKey: 'verdana' | 'georgia' | 'trebuchet' | 'tahoma';
  logo?: (number | null) | Media;
  banner?: (number | null) | Media;
  publicEnabled?: boolean | null;
  allowCrossDomainMove?: boolean | null;
  installedPackKey?: string | null;
  installedPackVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domain-memberships".
 */
export interface DomainMembership {
  id: number;
  /**
   * Canonical Domain relationship. Populated by the Phase 3 migration.
   */
  domain?: (number | null) | Domain;
  tenant?: (number | null) | Tenant;
  character: number | Character;
  status: 'active' | 'inactive';
  addedBy?: (number | null) | User;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domain-admins".
 */
export interface DomainAdmin {
  id: number;
  domain: number | Domain;
  user: number | User;
  status: 'active' | 'inactive';
  addedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subdomains".
 */
export interface Subdomain {
  id: number;
  domain: number | Domain;
  name: string;
  slug: string;
  description?: string | null;
  sortOrder?: number | null;
  headCharacter?: (number | null) | Character;
  adminCharacters?: (number | Character)[] | null;
  publicListing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subdomain-memberships".
 */
export interface SubdomainMembership {
  id: number;
  subdomain: number | Subdomain;
  character: number | Character;
  status: 'active' | 'inactive';
  addedBy?: (number | null) | User;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  domain: number | Domain;
  subdomain?: (number | null) | Subdomain;
  name: string;
  parentRole?: (number | null) | Role;
  active?: boolean | null;
  system?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "role-assignments".
 */
export interface RoleAssignment {
  id: number;
  character: number | Character;
  role: number | Role;
  scopeFolder?: (number | null) | Folder;
  status: 'active' | 'inactive';
  startsAt?: string | null;
  endsAt?: string | null;
  assignedBy: number | User;
  assignedByCharacter?: (number | null) | Character;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders".
 */
export interface Folder {
  id: number;
  /**
   * Canonical Domain relationship. Populated by the Phase 3 migration.
   */
  domain?: (number | null) | Domain;
  tenant?: (number | null) | Tenant;
  subdomain?: (number | null) | Subdomain;
  name: string;
  parent?: (number | null) | Folder;
  sortOrder?: number | null;
  /**
   * Domain root folders are protected from normal deletion or movement.
   */
  systemManaged?: boolean | null;
  filingPolicy: 'inherit' | 'direct-file' | 'review-required';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-types".
 */
export interface DocumentType {
  id: number;
  domain: number | Domain;
  name: string;
  description?: string | null;
  active?: boolean | null;
  defaultFilingPolicy: 'direct-file' | 'review-required';
  defaultFolder?: (number | null) | Folder;
  templateFilingPolicy: 'inherit' | 'direct-file' | 'review-required';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-provenance-events".
 */
export interface DocumentProvenanceEvent {
  id: number;
  domain: number | Domain;
  document: number | Document;
  actorUser?: (number | null) | User;
  actorCharacter?: (number | null) | Character;
  eventType:
    | 'created'
    | 'edited'
    | 'submitted'
    | 'filed'
    | 'approved'
    | 'rejected'
    | 'locked'
    | 'unlocked'
    | 'moved'
    | 'copied'
    | 'shared'
    | 'relationship-added'
    | 'relationship-removed'
    | 'deleted'
    | 'restored';
  occurredAt: string;
  /**
   * Structured before/after or workflow context.
   */
  context?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Payload revision ID, when available.
   */
  revisionId?: string | null;
  /**
   * External source identity, such as a future bridge event.
   */
  sourceDescriptor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Canonical Domain relationship. Populated by the Phase 3 migration.
   */
  domain?: (number | null) | Domain;
  tenant?: (number | null) | Tenant;
  documentType: number | DocumentType;
  /**
   * Archive folder. Leave empty to file at the root.
   */
  folder?: (number | null) | Folder;
  title: string;
  /**
   * Canonical Markdown body. Presentation (theme) is applied by the tenant, never stored here.
   */
  body: string;
  origin: 'web-editor' | 'markdown-import' | 'form';
  sourceKind: 'web' | 'markdown-import' | 'form' | 'copy' | 'correspondence' | 'second-life';
  lifecycle: 'draft' | 'pending_review' | 'filed' | 'locked';
  publicAccess: 'inherit' | 'private' | 'public';
  softDeletedAt?: string | null;
  softDeletedBy?: (number | null) | User;
  /**
   * Author, if known
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  user: number | User;
  tenant: number | Tenant;
  role: 'admin' | 'member';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Canonical Domain relationship. Populated by the Phase 3 migration.
   */
  domain?: (number | null) | Domain;
  tenant: number | Tenant;
  title: string;
  /**
   * URL identifier, e.g. about, home
   */
  slug: string;
  /**
   * Canonical Markdown body.
   */
  body: string;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'date';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Canonical Domain relationship. Populated by the Phase 3 migration.
   */
  domain?: (number | null) | Domain;
  tenant: number | Tenant;
  /**
   * Destination folder for generated documents.
   */
  folder?: (number | null) | Folder;
  archive: {
    /**
     * Output document title template, e.g. "{{incident_type}} Report - {{incident_date}}".
     */
    titleTemplate: string;
    /**
     * Output document Markdown template. {{field_name}} placeholders are replaced with submitted answers.
     */
    markdownTemplate: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'character-claim-requests';
        value: number | CharacterClaimRequest;
      } | null)
    | ({
        relationTo: 'character-merge-requests';
        value: number | CharacterMergeRequest;
      } | null)
    | ({
        relationTo: 'domain-character-contexts';
        value: number | DomainCharacterContext;
      } | null)
    | ({
        relationTo: 'domain-memberships';
        value: number | DomainMembership;
      } | null)
    | ({
        relationTo: 'domains';
        value: number | Domain;
      } | null)
    | ({
        relationTo: 'domain-admins';
        value: number | DomainAdmin;
      } | null)
    | ({
        relationTo: 'subdomains';
        value: number | Subdomain;
      } | null)
    | ({
        relationTo: 'subdomain-memberships';
        value: number | SubdomainMembership;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'role-assignments';
        value: number | RoleAssignment;
      } | null)
    | ({
        relationTo: 'document-types';
        value: number | DocumentType;
      } | null)
    | ({
        relationTo: 'document-provenance-events';
        value: number | DocumentProvenanceEvent;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'folders';
        value: number | Folder;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  slAvatarUUID?: T;
  slAvatarName?: T;
  slVerificationState?: T;
  slVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  name?: T;
  portrait?: T;
  bio?: T;
  controlledBy?: T;
  status?: T;
  mergedInto?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "character-claim-requests_select".
 */
export interface CharacterClaimRequestsSelect<T extends boolean = true> {
  character?: T;
  claimant?: T;
  tenant?: T;
  status?: T;
  requestedAt?: T;
  decidedAt?: T;
  decidedBy?: T;
  decidingCharacter?: T;
  decisionNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "character-merge-requests_select".
 */
export interface CharacterMergeRequestsSelect<T extends boolean = true> {
  source?: T;
  target?: T;
  tenant?: T;
  requestingUser?: T;
  requestingCharacter?: T;
  evidence?: T;
  note?: T;
  status?: T;
  decidingPlatformAdmin?: T;
  decisionReason?: T;
  requestedAt?: T;
  decidedAt?: T;
  impactPreviewHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domain-character-contexts_select".
 */
export interface DomainCharacterContextsSelect<T extends boolean = true> {
  domain?: T;
  tenant?: T;
  character?: T;
  localDisplayName?: T;
  localNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domain-memberships_select".
 */
export interface DomainMembershipsSelect<T extends boolean = true> {
  domain?: T;
  tenant?: T;
  character?: T;
  status?: T;
  addedBy?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains_select".
 */
export interface DomainsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  ownerUser?: T;
  ownerCharacter?: T;
  lifecycle?: T;
  defaultFilingPolicy?: T;
  motto?: T;
  preset?: T;
  primaryColor?: T;
  secondaryColor?: T;
  accentColor?: T;
  backgroundColor?: T;
  headingFontKey?: T;
  bodyFontKey?: T;
  logo?: T;
  banner?: T;
  publicEnabled?: T;
  allowCrossDomainMove?: T;
  installedPackKey?: T;
  installedPackVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domain-admins_select".
 */
export interface DomainAdminsSelect<T extends boolean = true> {
  domain?: T;
  user?: T;
  status?: T;
  addedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subdomains_select".
 */
export interface SubdomainsSelect<T extends boolean = true> {
  domain?: T;
  name?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  headCharacter?: T;
  adminCharacters?: T;
  publicListing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subdomain-memberships_select".
 */
export interface SubdomainMembershipsSelect<T extends boolean = true> {
  subdomain?: T;
  character?: T;
  status?: T;
  addedBy?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  domain?: T;
  subdomain?: T;
  name?: T;
  parentRole?: T;
  active?: T;
  system?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "role-assignments_select".
 */
export interface RoleAssignmentsSelect<T extends boolean = true> {
  character?: T;
  role?: T;
  scopeFolder?: T;
  status?: T;
  startsAt?: T;
  endsAt?: T;
  assignedBy?: T;
  assignedByCharacter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-types_select".
 */
export interface DocumentTypesSelect<T extends boolean = true> {
  domain?: T;
  name?: T;
  description?: T;
  active?: T;
  defaultFilingPolicy?: T;
  defaultFolder?: T;
  templateFilingPolicy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-provenance-events_select".
 */
export interface DocumentProvenanceEventsSelect<T extends boolean = true> {
  domain?: T;
  document?: T;
  actorUser?: T;
  actorCharacter?: T;
  eventType?: T;
  occurredAt?: T;
  context?: T;
  revisionId?: T;
  sourceDescriptor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  motto?: T;
  preset?: T;
  primaryColor?: T;
  secondaryColor?: T;
  accentColor?: T;
  backgroundColor?: T;
  headingFontKey?: T;
  bodyFontKey?: T;
  logo?: T;
  banner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  user?: T;
  tenant?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  domain?: T;
  tenant?: T;
  documentType?: T;
  folder?: T;
  title?: T;
  body?: T;
  origin?: T;
  sourceKind?: T;
  lifecycle?: T;
  publicAccess?: T;
  softDeletedAt?: T;
  softDeletedBy?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders_select".
 */
export interface FoldersSelect<T extends boolean = true> {
  domain?: T;
  tenant?: T;
  subdomain?: T;
  name?: T;
  parent?: T;
  sortOrder?: T;
  systemManaged?: T;
  filingPolicy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  domain?: T;
  tenant?: T;
  title?: T;
  slug?: T;
  body?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        date?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  domain?: T;
  tenant?: T;
  folder?: T;
  archive?:
    | T
    | {
        titleTemplate?: T;
        markdownTemplate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}